### PR TITLE
Add delete device script

### PR DESCRIPTION
**Pull request by AdrianaPineda**

### CODE REVIEW

**Comment by AdrianaPineda** [comment]
@mjabali can you take a look? Thanks!

**Comment by josh-authy** [comment]
@AdrianaPineda Can you change this so the API key is passed as part of the header instead of the URL?
e.g. -H "X-Authy-API-Key: $AUTHY_API_KEY"

**Comment by mjabali** [comment]
I'd also suggest that you add the utility description of:
echo Deleting TwilioAuth SDK User Device
instead of:
echo Delete a sdk device

**Comment by AdrianaPineda** [comment]
@josh-authy @mjabali updated code. Can you take a look again? Thanks!

**Pull request merged**
